name: "Issues from todo"

on:
    push:
        branches: [dev]
    workflow_dispatch:
        branches: [dev]
        inputs:
            MANUAL_COMMIT_REF:
                description: "The SHA of the commit to get the diff for"
                required: true
            MANUAL_BASE_REF:
                description: "By default, the commit entered above is compared to the one directly before it; to go back further, enter an earlier SHA here"
                required: false

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: "TODO to Issue"
              id: "todo"
              uses: "alstr/todo-to-issue-action@v4"
              env:
                  MANUAL_COMMIT_REF: ${{ inputs.MANUAL_COMMIT_REF }}
                  MANUAL_BASE_REF: ${{ inputs.MANUAL_BASE_REF }}
              with:
                  IDENTIFIERS: |
                      [
                          { "name": "TODO", "labels": ["todo"] },
                          { "name": "REFACTOR", "labels": ["todo"] },
                          { "name": "SUGGESTION", "labels": ["suggestion"] },
                          { "name": "IMPROVEMENT", "labels": ["enhancement"] },
                          { "name": "ENHANCEMENT", "labels": ["enhancement"] },
                      ]
